#!/bin/bash
# - reads a list of URLs and outputs an XML sitemap
# @author jonas.eberle@d-mind.de

#set -x

if [ -z "$2" ]; then
    echo Usage: "$0 ‹file with URLs› ‹sitemap.xml location›"
    exit 1
fi

urlsFilePath="$1"
shift
sitemapFilePath="$1"
shift

header='<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">'
echo $header > "$sitemapFilePath"
while read p; do
    case "$p" in
        */ | *.html | *.htm)
        echo '<url><changefreq>daily</changefreq><loc>'$p'</loc></url>' >> "$sitemapFilePath"
        ;;
    *)
        ;;
    esac
done < "$urlsFilePath"
echo "</urlset>" >> "$sitemapFilePath"
